const vscode = require("vscode");
const cfg = require("../core/configuration.js");
const { isDuskTheme } = require("./theme-common.js");
const log = require("../core/log.js");

// Rules we own inside `editor.tokenColorCustomizations`, tagged by `name` so we
// can update/remove them later WITHOUT ever touching the user's own rules.
const COMMENTS_RULE_NAME = "Dusk Office: comments";
const KEYWORDS_RULE_NAME = "Dusk Office: keywords";
const MANAGED_NAMES = [COMMENTS_RULE_NAME, KEYWORDS_RULE_NAME];

const COMMENT_SCOPES = [
  "comment",
  "comment.line",
  "comment.block",
  "comment.block.documentation",
  "punctuation.definition.comment",
];

const KEYWORD_SCOPES = [
  "keyword",
  "keyword.control",
  "storage.type",
  "storage.modifier",
];

// Build the override rules for the current settings. Dusk Office themes already
// ship italic comments and non-bold keywords, so we only emit a rule when the
// user deviates from that baseline (italic OFF, or bold ON).
function buildManagedRules() {
  const rules = [];
  if (!cfg.getSyntaxItalicComments()) {
    rules.push({
      name: COMMENTS_RULE_NAME,
      scope: COMMENT_SCOPES,
      settings: { fontStyle: "" },
    });
  }
  if (cfg.getSyntaxBoldKeywords()) {
    rules.push({
      name: KEYWORDS_RULE_NAME,
      scope: KEYWORD_SCOPES,
      settings: { fontStyle: "bold" },
    });
  }
  return rules;
}

function rulesEqual(a, b) {
  return JSON.stringify(a || []) === JSON.stringify(b || []);
}

/**
 * VS Code accepts `editor.tokenColorCustomizations` either as an object or as a
 * JSON string (the form generated by many configs). Coercing a string to `{}`
 * used to silently discard the user's entire customisation, so parse it and keep
 * the original shape when writing back.
 */
function readTokenColorCustomizations(current) {
  if (typeof current === "string") {
    const text = current.trim();
    if (text.length === 0) return { base: {}, asString: false };
    try {
      const parsed = JSON.parse(text);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        return { base: parsed, asString: true };
      }
    } catch {
      log.warn("applySyntaxStyle: tokenColorCustomizations is not parseable JSON, leaving it untouched");
    }
    // Unparseable or an unexpected shape — refuse to touch it rather than destroy it.
    return { base: null, asString: false };
  }
  if (current && typeof current === "object" && !Array.isArray(current)) {
    return { base: current, asString: false };
  }
  return { base: {}, asString: false };
}

// Reconcile `editor.tokenColorCustomizations` with the current syntax settings.
// Only active while a Dusk Office theme is selected; leaving Dusk themes removes
// our managed rules so other themes are never affected.
async function applySyntaxStyle() {
  try {
    const editorConfig = vscode.workspace.getConfiguration("editor");
    const { base, asString } = readTokenColorCustomizations(
      editorConfig.get("tokenColorCustomizations"),
    );
    if (base === null) return;
    const existingRules = Array.isArray(base.textMateRules)
      ? base.textMateRules
      : [];
    // Keep every rule the user defined; drop only our previously-managed ones.
    const userRules = existingRules.filter(
      (r) => !(r && MANAGED_NAMES.includes(r.name)),
    );

    const managed = isDuskTheme(cfg.getCurrentTheme())
      ? buildManagedRules()
      : [];
    const nextRules = [...userRules, ...managed];

    if (rulesEqual(existingRules, nextRules)) return;

    const next = { ...base };
    if (nextRules.length > 0) {
      next.textMateRules = nextRules;
    } else {
      delete next.textMateRules;
    }

    let valueToWrite;
    if (Object.keys(next).length > 0) {
      valueToWrite = asString ? JSON.stringify(next) : next;
    } else {
      valueToWrite = undefined;
    }
    await cfg.updateConfigValue(
      editorConfig,
      "tokenColorCustomizations",
      valueToWrite,
    );
  } catch (err) {
    log.error("applySyntaxStyle", err);
  }
}

async function toggleItalicComments() {
  try {
    const extCfg = cfg.getExtensionConfig();
    const next = !cfg.getSyntaxItalicComments();
    await cfg.updateConfigValue(extCfg, "syntax.italicComments", next);
    void vscode.window.showInformationMessage(
      next
        ? "Dusk Office: italic comments enabled."
        : "Dusk Office: italic comments disabled.",
    );
  } catch (err) {
    log.error("toggleItalicComments", err);
  }
}

async function toggleBoldKeywords() {
  try {
    const extCfg = cfg.getExtensionConfig();
    const next = !cfg.getSyntaxBoldKeywords();
    await cfg.updateConfigValue(extCfg, "syntax.boldKeywords", next);
    void vscode.window.showInformationMessage(
      next
        ? "Dusk Office: bold keywords enabled."
        : "Dusk Office: bold keywords disabled.",
    );
  } catch (err) {
    log.error("toggleBoldKeywords", err);
  }
}

module.exports = {
  applySyntaxStyle,
  toggleItalicComments,
  toggleBoldKeywords,
};
